"""4

Revision ID: 01f03f881ac4
Revises: c8a72427de70
Create Date: 2022-04-22 17:46:11.380457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f03f881ac4'
down_revision = 'c8a72427de70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_comment', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('post_favor', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('post_share', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_share', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('post_favor', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('post_comment', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
