"""3

Revision ID: 436a32c63afd
Revises: 458eb2da3121
Create Date: 2022-03-15 14:01:22.846868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436a32c63afd'
down_revision = '458eb2da3121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'name')
    # ### end Alembic commands ###
