"""4

Revision ID: b9fa4914cee0
Revises: 436a32c63afd
Create Date: 2022-03-22 09:54:33.896297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9fa4914cee0'
down_revision = '436a32c63afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('photo', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('user', 'deleted')
    op.drop_column('photo', 'deleted')
    op.drop_column('album', 'deleted')
    # ### end Alembic commands ###
